name: Run commitlint on PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-commit-lint-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install commitlint
        run: |
          npm install --global commitlint
          npm install --global @commitlint/config-conventional

      - name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
